name: nowcasting_dataset
channels:
  - pvlib
  - conda-forge
  - fastai
dependencies:
  - python>=3.9
  - pip
  - gitpython
  - pydantic

  # Scientific Python
  - numpy
  - pandas
  - matplotlib
  - zarr
  - xarray
  - ipykernel
  - h5netcdf # For opening NetCDF files from cloud buckets.
  - fastai::opencv-python-headless

  # Cloud & distributed compute
  - gcsfs
  - fsspec
  - pathy

  # PV & Geospatial
  - pvlib
  - pyproj
  - rioxarray
  - geopandas
  - pyresample

  # Development tools
  - pytest
  - flake8
  - jedi
  - mypy
  - black
  - pre-commit

  - pip:
      - git+https://github.com/SheffieldSolar/PV_Live-API
