name: Test Docker image
on:
  push:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  push_to_registry:
    name: Build docker file for testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker-compose -f test-docker-compose.yml build

      - name: Run tests inside the container
        run: docker-compose -f test-docker-compose.yml run dataseet

      - name: Copy coverage
        run: |
          # copy file
          mv ./tests/.coverage .
          mv ./tests/coverage.xml .

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
